In [20]:
import pandas as pd
import numpy as np
import dtale

In [21]:
df = pd.read_csv("final_feature.csv", sep = ";")

In [22]:
df1 = df.copy()

In [23]:
df2 = df1.fillna(0)
df3 = df1.drop(["features_smile.nombre_profil","features_smile.nombre_fois_profil_change","features_smile.profil","features_smile.nombre_souscription","features_smile.nombre_pass_achete"], axis = 1)

In [24]:
df3

,features_smile.msisdn,features_smile.nombre_sms_sortants,features_smile.nombre_correspondant_sms_sortant,features_smile.nombre_appels_sortants,features_smile.nombre_correspondant_appels_sortant,features_smile.nombre_correspondant_distinct_appels_sortant,features_smile.duree_totale_appel_sortant,features_smile.duree_moyenne_appel_sortant,features_smile.nombre_sms_entrants,features_smile.nombre_correspondant_sms_entrant,...,features_smile.numb_inter_correp_out,features_smile.time_call_out,features_smile.numb_call_inter_out,features_smile.numb_inter_correp_in_distinct,features_smile.numb_inter_correp_in,features_smile.time_call_in,features_smile.numb_call_inter_in,features_smile.numb_inter_corresp_distinct,features_smile.numb_inter_correp,features_smile.numb_call_inter
0,22502251164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22502252230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22507006396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,22507007067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22507008914,592.0,197.0,694.0,582.0,197.0,2364990.0,3864.362745,19.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761751,22598489491,33.0,40.0,482.0,170.0,40.0,65855.0,387.382353,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1761752,22598492310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1761753,22598493044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1761754,22598494167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1761755,22598497426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df4 = df3.fillna(0)

In [26]:
dtale.show(df3)

In [27]:
col = [i.replace('features_smile.', '') for i in df3.columns.to_list()]
col

['msisdn',
 'nombre_sms_sortants',
 'nombre_correspondant_sms_sortant',
 'nombre_appels_sortants',
 'nombre_correspondant_appels_sortant',
 'nombre_correspondant_distinct_appels_sortant',
 'duree_totale_appel_sortant',
 'duree_moyenne_appel_sortant',
 'nombre_sms_entrants',
 'nombre_correspondant_sms_entrant',
 'nombre_appel_entrants',
 'nombre_correspondant_appel_entrant',
 'nombre_correspondant_appel_distinct_entrant',
 'duree_totale_appel_entrant',
 'duree_moyenne_appel_entrant',
 'nombre_sms',
 'nombre_appels',
 'nombre_correspondants_sms',
 'nombre_correspondants',
 'nombre_correspondants_distincts',
 'nombre_correspondants_distincts_appels',
 'nombre_correspondants_appels',
 'duree_totale_appels',
 'duree_moyenne_appels',
 'taux_inities_sms',
 'nombre_appels_onnet',
 'taux_appels_inities_onnet',
 'nombre_appels_offnet',
 'taux_appels_inities_offnet',
 'nombre_appels_inter',
 'taux_appels_inities_inter',
 'nombre_appels_complice',
 'taux_appels_inities_complice',
 'nbre_imsi',
 'nbre_distinct_imei',
 'ratio_nombre_imsi_imei',
 'nombre_appels_nuit',
 'nombre_appels_nuit_distinct',
 'temps_moyen_evenement',
 'variance_evenement',
 'temps_moyen_appel',
 'variance_appel',
 'temps_moyen_sms',
 'variance_sms',
 'totaldureeusedata',
 'nbre_sim',
 'supplier_name',
 'nombre_cal_onnet',
 'nbre_moy_cal_onnet',
 'duree_moy_cal_onnet',
 'duree_cal_onnet',
 'nbre_moy_cal_offnet',
 'nombre_cal_offnet',
 'duree_moy_cal_offnet',
 'duree_cal_offnet',
 'duree_mean_call_out',
 'ratio_corresp_out_in',
 'ratio_call_out_in',
 'numb_inter_correp_out_distinct',
 'numb_inter_correp_out',
 'time_call_out',
 'numb_call_inter_out',
 'numb_inter_correp_in_distinct',
 'numb_inter_correp_in',
 'time_call_in',
 'numb_call_inter_in',
 'numb_inter_corresp_distinct',
 'numb_inter_correp',
 'numb_call_inter']

In [28]:
df3.columns = col

In [29]:
df_pass = pd.read_csv("features_pass_souscription_profil.csv", delimiter = ";")

In [30]:
df_pass

,features_pass_souscription_profil.msisdn,features_pass_souscription_profil.nombre_profil,features_pass_souscription_profil.nombre_fois_profil_change,features_pass_souscription_profil.profil,features_pass_souscription_profil.nombre_souscription,features_pass_souscription_profil.nombre_pass_achete
0,22507004594,1.0,0.0,Basic Price Plan [for all Brands],5.0,12.0
1,22507007581,NaN,NaN,NaN,NaN,NaN
2,22507008616,1.0,0.0,TIGRE,3.0,4.0
3,22507009220,1.0,0.0,Kit_Classic,3.0,3.0
4,22507019241,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
1761751,22598495295,NaN,NaN,NaN,NaN,NaN
1761752,22598497297,NaN,NaN,NaN,NaN,NaN
1761753,22598498483,NaN,NaN,NaN,NaN,NaN
1761754,22598499639,NaN,NaN,NaN,NaN,NaN
1761755,22598499640,NaN,NaN,NaN,NaN,NaN

In [31]:
df_pass = df_pass.fillna(0)

In [32]:
coll = [i.replace('features_pass_souscription_profil.', '') for i in df_pass.columns.to_list()]
coll

['msisdn',
 'nombre_profil',
 'nombre_fois_profil_change',
 'profil',
 'nombre_souscription',
 'nombre_pass_achete']

In [33]:
df_pass.columns = coll

In [34]:
df_pass = df_pass.drop('msisdn', axis = 1)

In [35]:
df5 = pd.concat([df3, df_pass], axis=1, join='inner')
df5

,msisdn,nombre_sms_sortants,nombre_correspondant_sms_sortant,nombre_appels_sortants,nombre_correspondant_appels_sortant,nombre_correspondant_distinct_appels_sortant,duree_totale_appel_sortant,duree_moyenne_appel_sortant,nombre_sms_entrants,nombre_correspondant_sms_entrant,...,time_call_in,numb_call_inter_in,numb_inter_corresp_distinct,numb_inter_correp,numb_call_inter,nombre_profil,nombre_fois_profil_change,profil,nombre_souscription,nombre_pass_achete
0,22502251164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,Basic Price Plan [for all Brands],5.0,12.0
1,22502252230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0
2,22507006396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,TIGRE,3.0,4.0
3,22507007067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,Kit_Classic,3.0,3.0
4,22507008914,592.0,197.0,694.0,582.0,197.0,2364990.0,3864.362745,19.0,13.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761751,22598489491,33.0,40.0,482.0,170.0,40.0,65855.0,387.382353,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0
1761752,22598492310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0
1761753,22598493044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0
1761754,22598494167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0
1761755,22598497426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0

In [17]:
#df5 = df5.fillna(0)

In [36]:
dtale.show(df5)

In [39]:
display(df5.isnull().sum())

msisdn                                      0
nombre_sms_sortants                    946286
nombre_correspondant_sms_sortant       946286
nombre_appels_sortants                 946286
nombre_correspondant_appels_sortant    946286
                                        ...
nombre_profil                               0
nombre_fois_profil_change                   0
profil                                      0
nombre_souscription                         0
nombre_pass_achete                          0
Length: 74, dtype: int64

Executing shutdown due to inactivity...

2021-03-29 10:41:35,244 - INFO     - Executing shutdown due to inactivity...

Executing shutdown...

2021-03-29 10:41:35,406 - INFO     - Executing shutdown...

In [ ]:
s = df['nombre_appels']
q1 = s.quantile(0.25)
q3 = s.quantile(0.75)
iqr = q3 - q1
iqr_lower = q1 - 1.5 * iqr
iqr_upper = q3 + 1.5 * iqr
outliers = dict(s[(s < iqr_lower) | (s > iqr_upper)])

In [18]:
#df5.to_csv('good_final.csv')

In [15]:
#df5 = df5.fillna(0)

In [41]:
df6 = pd.read_csv("file1.csv")
df6

,Unnamed: 0,msisdn,nombre_sms_sortants,nombre_correspondant_sms_sortant,nombre_appels_sortants,nombre_correspondant_appels_sortant,nombre_correspondant_distinct_appels_sortant,duree_totale_appel_sortant,duree_moyenne_appel_sortant,nombre_sms_entrants,...,time_call_in,numb_call_inter_in,numb_inter_corresp_distinct,numb_inter_correp,numb_call_inter,nombre_profil,nombre_fois_profil_change,profil,nombre_souscription,nombre_pass_achete
0,0,22502251164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,Basic Price Plan [for all Brands],5.0,12.0
1,1,22502252230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,22507006396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,TIGRE,3.0,4.0
3,3,22507007067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,Kit_Classic,3.0,3.0
4,4,22507008914,592.0,197.0,694.0,582.0,197.0,2364990.0,3864.362745,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761751,1761751,22598489491,33.0,40.0,482.0,170.0,40.0,65855.0,387.382353,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1761752,1761752,22598492310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1761753,1761753,22598493044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1761754,1761754,22598494167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1761755,1761755,22598497426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
dtale.show(df6)

In [47]:
df6[df6['nombre_sms']>174.5].shape

(119414, 75)

Executing shutdown due to inactivity...
Executing shutdown due to inactivity...

2021-03-30 14:56:33,162 - INFO     - Executing shutdown due to inactivity...

Executing shutdown...
Executing shutdown...

2021-03-30 14:56:33,588 - INFO     - Executing shutdown...

In [21]:
df6.shape

(1761756, 75)

In [20]:
df6.isnull().sum(axis = 0)

Unnamed: 0                                0
msisdn                                    0
nombre_sms_sortants                  946286
nombre_correspondant_sms_sortant     946286
nombre_appels_sortants               946286
                                     ...
nombre_profil                       1361701
nombre_fois_profil_change           1361701
profil                              1361701
nombre_souscription                 1361701
nombre_pass_achete                  1361701
Length: 75, dtype: int64

In [23]:
import lux

In [24]:
dff = pd.read_csv('file1.csv')
dff.head()

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit, y: ratio_corresp_out_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit, y: taux_appels_inities_inter) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit, y: duree_mean_call_out) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit, y: numb_call_inter_out) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit, y: numb_inter_correp_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit, y: numb_inter_correp) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: ratio_call_out_in, y: nombre_appels_nuit) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: time_call_in, y: nombre_appels_nuit) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nbre_sim, y: ratio_corresp_out_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nbre_sim, y: duree_mean_call_out) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nbre_sim, y: numb_call_inter_out) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nbre_sim, y: numb_inter_correp_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nbre_sim, y: numb_inter_correp) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nbre_sim, y: ratio_call_out_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nbre_sim, y: time_call_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: time_call_out, y: nombre_appels_nuit) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: time_call_out, y: nbre_sim) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: numb_inter_corresp_distinct, y: nombre_appels_nuit) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: numb_inter_corresp_distinct, y: nbre_sim) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: numb_call_inter_in, y: nombre_appels_nuit) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: numb_call_inter_in, y: nbre_sim) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: numb_inter_correp_in_distinct, y: nombre_appels_nuit) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: numb_inter_correp_in_distinct, y: nbre_sim) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: numb_call_inter, y: nombre_appels_nuit) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: numb_call_inter, y: nbre_sim) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: ratio_corresp_out_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: taux_appels_inities_inter) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: duree_mean_call_out) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: numb_call_inter_out) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: numb_inter_correp_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: numb_inter_correp) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: ratio_call_out_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: time_call_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: time_call_out) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: numb_inter_corresp_distinct) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: numb_call_inter_in) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: numb_inter_correp_in_distinct) mark: scatter, score: 0.0 >

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/lux/interestingness/interestingness.py:166: UserWarning:An error occurred when computing interestingness for: <Vis  (x: nombre_appels_nuit_distinct, y: numb_call_inter) mark: scatter, score: 0.0 >
/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py:345: UserWarning:
Lux defaults to Pandas when there are no valid actions defined.

,Unnamed: 0,msisdn,nombre_sms_sortants,nombre_correspondant_sms_sortant,nombre_appels_sortants,nombre_correspondant_appels_sortant,nombre_correspondant_distinct_appels_sortant,duree_totale_appel_sortant,duree_moyenne_appel_sortant,nombre_sms_entrants,...,time_call_in,numb_call_inter_in,numb_inter_corresp_distinct,numb_inter_correp,numb_call_inter,nombre_profil,nombre_fois_profil_change,profil,nombre_souscription,nombre_pass_achete
0,0,22502251164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,Basic Price Plan [for all Brands],5.0,12.0
1,1,22502252230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,22507006396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,TIGRE,3.0,4.0
3,3,22507007067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,Kit_Classic,3.0,3.0
4,4,22507008914,592.0,197.0,694.0,582.0,197.0,2364990.0,3864.362745,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
dff.info()

<class 'lux.core.frame.LuxDataFrame'>
RangeIndex: 1761756 entries, 0 to 1761755
Data columns (total 75 columns):
 #   Column                                        Dtype
---  ------                                        -----
 0   Unnamed: 0                                    int64
 1   msisdn                                        int64
 2   nombre_sms_sortants                           float64
 3   nombre_correspondant_sms_sortant              float64
 4   nombre_appels_sortants                        float64
 5   nombre_correspondant_appels_sortant           float64
 6   nombre_correspondant_distinct_appels_sortant  float64
 7   duree_totale_appel_sortant                    float64
 8   duree_moyenne_appel_sortant                   float64
 9   nombre_sms_entrants                           float64
 10  nombre_correspondant_sms_entrant              float64
 11  nombre_appel_entrants                         float64
 12  nombre_correspondant_appel_entrant            float64
 13  nombre_correspondant_appel_distinct_entrant   float64
 14  duree_totale_appel_entrant                    float64
 15  duree_moyenne_appel_entrant                   float64
 16  nombre_sms                                    float64
 17  nombre_appels                                 float64
 18  nombre_correspondants_sms                     float64
 19  nombre_correspondants                         float64
 20  nombre_correspondants_distincts               float64
 21  nombre_correspondants_distincts_appels        float64
 22  nombre_correspondants_appels                  float64
 23  duree_totale_appels                           float64
 24  duree_moyenne_appels                          float64
 25  taux_inities_sms                              float64
 26  nombre_appels_onnet                           float64
 27  taux_appels_inities_onnet                     float64
 28  nombre_appels_offnet                          float64
 29  taux_appels_inities_offnet                    float64
 30  nombre_appels_inter                           float64
 31  taux_appels_inities_inter                     float64
 32  nombre_appels_complice                        float64
 33  taux_appels_inities_complice                  float64
 34  nbre_imsi                                     float64
 35  nbre_distinct_imei                            float64
 36  ratio_nombre_imsi_imei                        float64
 37  nombre_appels_nuit                            float64
 38  nombre_appels_nuit_distinct                   float64
 39  temps_moyen_evenement                         float64
 40  variance_evenement                            float64
 41  temps_moyen_appel                             float64
 42  variance_appel                                float64
 43  temps_moyen_sms                               float64
 44  variance_sms                                  float64
 45  totaldureeusedata                             float64
 46  nbre_sim                                      float64
 47  supplier_name                                 object
 48  nombre_cal_onnet                              float64
 49  nbre_moy_cal_onnet                            float64
 50  duree_moy_cal_onnet                           float64
 51  duree_cal_onnet                               float64
 52  nbre_moy_cal_offnet                           float64
 53  nombre_cal_offnet                             float64
 54  duree_moy_cal_offnet                          float64
 55  duree_cal_offnet                              float64
 56  duree_mean_call_out                           float64
 57  ratio_corresp_out_in                          float64
 58  ratio_call_out_in                             float64
 59  numb_inter_correp_out_distinct                float64
 60  numb_inter_correp_out                         float64
 61  time_call_out                                 float64
 62  numb_call_inter_out                           float64
 63  numb_inter_correp_in_distinct                 float64
 64  numb_inter_correp_in                          float64
 65  time_call_in                                  float64
 66  numb_call_inter_in                            float64
 67  numb_inter_corresp_distinct                   float64
 68  numb_inter_correp                             float64
 69  numb_call_inter                               float64
 70  nombre_profil                                 float64
 71  nombre_fois_profil_change                     float64
 72  profil                                        object
 73  nombre_souscription                           float64
 74  nombre_pass_achete                            float64
dtypes: float64(71), int64(2), object(2)
memory usage: 1008.1+ MB

In [26]:
dfr = dff.fillna(0)

In [27]:
dfr

,Unnamed: 0,msisdn,nombre_sms_sortants,nombre_correspondant_sms_sortant,nombre_appels_sortants,nombre_correspondant_appels_sortant,nombre_correspondant_distinct_appels_sortant,duree_totale_appel_sortant,duree_moyenne_appel_sortant,nombre_sms_entrants,...,time_call_in,numb_call_inter_in,numb_inter_corresp_distinct,numb_inter_correp,numb_call_inter,nombre_profil,nombre_fois_profil_change,profil,nombre_souscription,nombre_pass_achete
0,0,22502251164,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Basic Price Plan [for all Brands],5.0,12.0
1,1,22502252230,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
2,2,22507006396,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,TIGRE,3.0,4.0
3,3,22507007067,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Kit_Classic,3.0,3.0
4,4,22507008914,592.0,197.0,694.0,582.0,197.0,2364990.0,3864.362745,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761751,1761751,22598489491,33.0,40.0,482.0,170.0,40.0,65855.0,387.382353,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
1761752,1761752,22598492310,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
1761753,1761753,22598493044,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
1761754,1761754,22598494167,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
1761755,1761755,22598497426,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0

Executing shutdown due to inactivity...

2021-03-25 13:42:02,773 - INFO     - Executing shutdown due to inactivity...

Executing shutdown...

2021-03-25 13:42:03,027 - INFO     - Executing shutdown...

In [1]:
import requests
import lxml.html as lh
import pandas as pd

In [2]:
url='http://www.maxifoot.fr/classement-buteur-europe.htm'
#Create a handle, page, to handle the contents of the website
page = requests.get(url)
#Store the contents of the website under doc
doc = lh.fromstring(page.content)
#Parse data that are stored between <tr>..</tr> of HTML
tr_elements = doc.xpath('//tr')

In [6]:
#Create empty list
col=[]
i=0
#For each row, store each first element (header) and an empty list
for t in tr_elements:
    #i+=1
    name=t.text_content()
    print(name)
    #print('%d:"%s"'%(i,name))
    #col.append((name,[]))

if (ad1) { document.write('<div id="crt-4fe33ba0" style="width:728px;height:90px;"></div>'); }



googletag.cmd.push(function() {  googletag.display('div-gpt-ad-1361437281826-0'); });



OMPSGLyonLilleBordeauxASSEChelseaMan
UtdArsenalLiverpoolManCityBarcaRealAtleticoMilanJuveInterBayernDortmund+ de clubs


Résultats
Classements
Calendriers



MercatoActualité |
Journal des Transferts |
Tableaux des transferts Ligue 1 |
Tableaux des transferts Etrangers |
Ligue 1Actualité |
Résultats & Classement |
Buteurs |
Calendrier |
Equipe type |
Tableau Transferts |
Palmarès |
Les Clubs |
L2/CoupesRésultats Ligue 2 |
Résus National |
Résus Coupe de France |
Résus Coupe de la Ligue |
Actu Coupe de France |
Actu Coupe de la Ligue |
EtrangerAngleterre |
Espagne |
Italie |
Allemagne |
Belgique |
Pays-Bas |
Portugal |
Turquie |
Suisse |
Algérie |
Maroc |
Tunisie |
Coupe d'EuropeLigue des Champions |
Ligue Europa |
Buteurs |
Coefficients UEFA |
Palmarès C1 |
Palmarès C3 |
Les Bleus & InternationalActu des Bleus |
Class. FIFA |
Mondial 2018 |
CAN 2017 |
Euro 2016 |
CM 2014 |
Palmarès Mondial |
Palmarès Euro |
Ballon d'Or |
ChroniquesJournal des Transferts |
Baromètre |
Débat du Jeudi |
Portraits |
TOP Déclarations |
Interviews |
36 de Maxifoot |
 TV Programme TV foot |
 + Liens foot |
Flux RSS |
Sondages foot |
Vidéo foot |




RESULTATS

1Lille76 pts
2Paris SG75 pts
3Monaco71 pts
1Troyes74 pts
2Clermont F.69 pts
3Toulouse62 pts
1Manchester City80 pts
2Manchester Utd67 pts
3Leicester City63 pts
1Atl. Madrid76 pts
2Real Madrid74 pts
3FC Barcelone74 pts
1Inter Milan82 pts
2Atalanta Bergame69 pts
3Juventus Turin69 pts
1Bayern Munich71 pts
2RB Leipzig64 pts
3Wolfsbourg57 pts


.titcomp { font:bold 24px/24px arial,tahoma; color:#008; padding:0 0 8px 0; display:inline-block; }
table.butd1 { border-collapse:collapse; background:#fff; font:12px/18px arial; color:#000; border:1px solid #ccc; border-top:0; width:658px; }
.butd1 td { padding:0px; }
.butd1 th { font:bold 13px arial; color:#f14; background-color:#f6f6f6; padding:6px 0 6px 4px; }
.butd1 td.p1 { text-align:right; padding-right:6px; }
.butd1 td.e1 { color:#666; font-style:italic; }
.butd1 td.b1 { font:bold 13px/12px arial; padding:5px 10px 6px 12px; text-align:left; white-space:nowrap; }
.butd1 td.mo1, .butd1 th.mo1 { text-align:right; padding-right:6px; }
.butd1 td i, .butd1 td i a { color:#666; font:11px arial; }
.butd1 td img { width:16px; height:16px; position:relative; top:3px; }
.butd1 tr.cl1 { background:#eee; }
.butd1 a.eqb { color:#666; text-decoration:none; }
.butd1 a.eqb:hover { color:#009; text-decoration:underline; }
.butd1 a.jou1 { text-decoration:none; color:#000; }
.butd1 a.jou1:hover { text-decoration:underline; }


EUROPE, 5 pays majeurs - Saison 2020-21
Classement des buteurs (en savoir plus)


#mb6 img { background:url(//flag.maxifoot-live.com/sprite_flag.png) no-repeat; display:inline-block; width:18px; height:12px; }
#mb6 .fl-be { background-position:0 0; }
#mb6 .fl-ch { background-position:-18px 0; }
#mb6 .fl-de { background-position:-36px 0; }
#mb6 .fl-en { background-position:-54px 0; }
#mb6 .fl-es { background-position:-72px 0; }
#mb6 .fl-eu { background-position:-90px 0; }
#mb6 .fl-fr { background-position:-108px 0; }
#mb6 .fl-gr { background-position:-126px 0; }
#mb6 .fl-it { background-position:-144px 0; }
#mb6 .fl-ldc { background-position:-162px 0; }
#mb6 .fl-nl { background-position:-180px 0; }
#mb6 .fl-pt { background-position:-198px 0; }
#mb6 .fl-sc { background-position:-216px 0; }
#mb6 .fl-tk { background-position:-235px 0; }
#mb5 { display:none; width:200px; text-align:left; position:relative; z-index:999; }
#mb5 a.mb2 { display:block; text-decoration:none; font:12px/20px arial; border-top:2px solid #e4e4e4; border-bottom:1px solid #999; border-left:1px solid #ccc;
 border-right:1px solid #999; text-align:center; color:#000; border-radius:2px; background:url(/0_images/select_bg.gif) repeat-x; width:198px; }
#mb5 a.mb2:hover { color:#990; box-shadow:0 0 2px #000; }
#mb6 { display:none; border:1px solid #999; border-left-color:#ccc; position:absolute; border-top-width:0; width:200px; box-shadow:0 0 2px #000; }
#mb6 a { display:block; font:12px arial; padding:3px; background:#f9f9f9; text-decoration:none; color:#000; text-align:left; }
#mb6 a img { position:relative; top:1px; }
#mb6 a:hover { background:#00c; color:#fff; }


function onmb1(mb1) {
        if (mb1==1) { var mb1='block'; } else { var mb1='none'; }
        document.getElementById('mb6').style.display=mb1;
}


Choisir une autre compétition

 TOP EUROPE (Chp. + Coupes)

 FRANCE - Ligue 1
 FRANCE - Ligue 2
 ANGL. - Premier League
 ALLEMAGNE - Bundesliga
 ESPAGNE - Liga
 ITALIE - Serie A

 LIGUE des CHAMPIONS
 LIGUE EUROPA

 MONDIAL 2018 - RUSSIE
 EURO 2016
 EURO 2016 - Qualifs
 MONDIAL 2014 - BRESIL
 CM 2014 - Qualifications
 EURO 2012

 BELGIQUE - Lig. Jupiler
 ECOSSE - Pr. League
 GRECE - Super Ligue
 PAYS-BAS - Eredivisie
 PORTUGAL - Liga 1
 SUISSE - Super League
 TURQUIE - Super Ligi



document.getElementById('mb5').style.display='inline-block';





.ong1 { border:1px solid #bbb; border-width:1px 1px 0px 1px; display:inline-block; padding:0 1px; }
.ong1 a { background:#e6e6e6; display:inline-block; color:#666; text-decoration:none; font:bold 11px/18px tahoma; padding:0 10px; border:1px solid #fff; }
.ong1 a:hover { background:#fff; color:#f14; }
.ong1 a.a2 { background:#ccc; border-bottom:1px solid #ccc; color:#000; }
.ong1 a.a2:hover { background:#ccc; border-bottom:1px solid #ccc; color:#000; }
.ong1 a img { position:relative; top:2px; opacity:0.5; filter:alpha(opacity=50); }
.ong1 a.a2 img { opacity:1; filter:alpha(opacity=100); }
.ong1 .ong2 { display:inline-block; border-bottom:0; }
#selsais1 { width:658px; height:30px; display:block; background:#ccc; border-bottom:0px solid #ccc; overflow:hidden; }
#selsais1 .activ1 { color:#000; font:13px/20px arial; margin:4px 0 0 8px; display:inline-block; width:190px; }
#selsais1 a.m1 img { border:0; position:relative; top:3px; border-radius:2px; z-index:2; }
#selsais1 .sela1 { font:13px/20px arial; background:#b3b3b3; border:1px solid #eee; padding:0; border-radius:5px; margin:4px 8px 0 8px; text-align:left; }
#selsais1 .sela1 a.m1 { text-decoration:none; color:#333; display:block; padding:0 4px 0 6px; }
#selsais1 .sela1 a.sel1 { background:#ff9; color:#000; border-radius:4px; }
#mb6a, #mb6b, #mb6c { display:none; border:1px solid #999; background:#ccc; position:absolute; z-index:999; text-align:left; box-shadow:1px 1px 3px #000; padding:4px 0; }
#mb6a a, #mb6b a, #mb6c a { display:block; font:12px/20px arial; padding:2px 6px; text-decoration:none; color:#000; text-align:center; }
#mb6a a:hover, #mb6b a:hover, #mb6c a:hover { background:#00c; color:#fff; }
#mb6a { width:120px; }
#mb6b { width:200px; }
#mb6c { width:180px; }
.ong2 img { background-image:url(//flag.maxifoot-live.com/sprite_flag.png); background-repeat:no-repeat; display:inline-block; width:18px; height:12px; }
.fl-be { background-position:0 0; }
.fl-ch { background-position:-18px 0; }
.fl-de { background-position:-36px 0; }
.fl-en { background-position:-54px 0; }
.fl-es { background-position:-72px 0; }
.fl-fr { background-position:-108px 0; }
.fl-gr { background-position:-126px 0; }
.fl-it { background-position:-144px 0; }
.fl-nl { background-position:-180px 0; }
.fl-pt { background-position:-198px 0; }
.fl-sc { background-position:-216px 0; }
.fl-tk { background-position:-235px 0; }



TOP 5






France - Angl. - Esp. - Italie - All.
TOP 12  ( Top 5 +






 )

Portugal - Pays-Bas - Belg. - Suis. - Turq. - Grèc. - Ecos.



  Mis à jour le mar. 04/05/2021 à 02h08

function onmb1(mb1) {
        if (mb1==1) { var mb1='block'; } else { var mb1='none'; }
        document.getElementById('mb6').style.display=mb1;
}


	Saison 2020-21

saison 2020-21
saison 2019-20
saison 2018-19
saison 2017-18
saison 2016-17
saison 2015-16
saison 2014-15
saison 2013-14
saison 2012-13
saison 2011-12
saison 2010-11



function onmb1a(mb1) {
	if (mb1==1) { var mb1='inline-block'; } else { var mb1='none'; }
	document.getElementById('mb6a').style.display=mb1;
}
document.getElementById('mb5a').style.display='inline-block';

	classement par ANNÉE civile

année civile 2021
année civile 2020
année civile 2019
année civile 2018
année civile 2017
année civile 2016
année civile 2015
année civile 2014
année civile 2013
année civile 2012
année civile 2011



function onmb1b(mb1) {
	if (mb1==1) { var mb1='inline-block'; } else { var mb1='none'; }
	document.getElementById('mb6b').style.display=mb1;
}
document.getElementById('mb5b').style.display='inline-block';

	CUMULÉ sur N saisons

CUMUL 6 saisons, 2015-2021
CUMUL 5 saisons, 2016-2021
CUMUL 4 saisons, 2017-2021
CUMUL 3 saisons, 2018-2021
CUMUL 2 saisons, 2019-2021




function onmb1c(mb1) {
	if (mb1==1) { var mb1='inline-block'; } else { var mb1='none'; }
	document.getElementById('mb6c').style.display=mb1;
}
document.getElementById('mb5c').style.display='inline-block';


Pl.JoueurEquipe
Butsdont champ.MatchsMin/But(*)
1. R. LEWANDOWSKI Bayern Munich   43 (8 p.)36   37 (1,16 b/m)73'2. E. HAALAND Borussia Dortmund   37 (3 p.)25   38 (0,97 b/m)88'. K. MBAPPÉ  Paris SG   37 (9 p.)25   43 (0,86 b/m)91'4. L. MESSI FC Barcelone   36 (7 p.)28   44 (0,82 b/m)109'5. CRISTIANO RONALDO Juventus Turin   34 (9 p.)27   40 (0,85 b/m)100'6. H. KANE Tottenham   31 (6 p.)21   45 (0,69 b/m)117'7. MOHAMED SALAH Liverpool   29 (7 p.)20   46 (0,63 b/m)130'8. K. BENZEMA  Real Madrid   28 (1 p.)21   41 (0,68 b/m)123'9. R. LUKAKU Inter Milan   27 (6 p.)21   41 (0,66 b/m)124'10. ANDRÉ SILVA Eintracht Francfort   26 (6 p.)25   31 (0,84 b/m)103'. GERARD MORENO Villarreal   26 (11 p.)20   39 (0,67 b/m)118'. BRUNO FERNANDES Manchester Utd   26 (12 p.)16   52 (0,50 b/m)158'13. W. WEGHORST Wolfsbourg   25 (2 p.)20   38 (0,66 b/m)131'14. C. IMMOBILE Lazio Rome   24 (7 p.)19   37 (0,65 b/m)123'15. L. MURIEL Atalanta Bergame   23 (2 p.)19   43 (0,53 b/m)83'. Y. EN-NESYRI FC Seville   23 (1 p.)17   48 (0,48 b/m)120'17. A. KRAMARIC Hoffenheim   22 (7 p.)17   31 (0,71 b/m)113'18. M. DEPAY Lyon   21 (8 p.)19   38 (0,55 b/m)140'. SON HEUNG-MIN Tottenham   21 (1 p.)16   47 (0,45 b/m)173'20. W. BEN YEDDER  Monaco   20 (11 p.)19   36 (0,56 b/m)129'. D. CALVERT-LEWIN Everton   2015   34 (0,59 b/m)143'. M. RASHFORD Manchester Utd   20 (1 p.)10   51 (0,39 b/m)189'23. S. NWANKWO Crotone   19 (8 p.)19   35 (0,54 b/m)138'. L. SUÁREZ Atl. Madrid   19 (3 p.)19   34 (0,56 b/m)138'. D. VLAHOVIC Fiorentina   19 (6 p.)19   36 (0,53 b/m)144'. A. GRIEZMANN  FC Barcelone   19 (1 p.)12   47 (0,40 b/m)188'27. M. KEAN Paris SG / Everton (2)   18 (1 p.)12   40 (0,45 b/m)129'. MORATA Juventus Turin   18 (2 p.)9   41 (0,44 b/m)146'. K. VOLLAND Monaco   1816   35 (0,51 b/m)157'. D. ZAPATA Atalanta Bergame   18 (1 p.)14   44 (0,41 b/m)158'31. Z. IBRAHIMOVIC Milan AC   17 (3 p.)15   26 (0,65 b/m)110'. K. IHEANACHO Leicester City   1710   34 (0,50 b/m)111'. A. LACAZETTE  Arsenal   17 (4 p.)13   39 (0,44 b/m)141'. L. MARTÍNEZ Inter Milan   1715   44 (0,39 b/m)176'. L. INSIGNE Naples   17 (7 p.)17   44 (0,39 b/m)197'36. A. DELORT Montpellier   16 (1 p.)13   30 (0,53 b/m)155'. B. DIA Reims   16 (5 p.)14   36 (0,44 b/m)183'. I. GÜNDOGAN Manchester City   16 (1 p.)12   41 (0,39 b/m)190'. A. GOUIRI  Nice   16 (4 p.)12   38 (0,42 b/m)194'40. L. ALARIO Bayer Leverkusen   15 (3 p.)11   33 (0,45 b/m)113'. T. MOFFI Lorient   15 (1 p.)14   31 (0,48 b/m)126'. B. YILMAZ Lille   15 (2 p.)13   30 (0,50 b/m)129'. NEYMAR Paris SG   15 (5 p.)7   26 (0,58 b/m)131'. S. KALAJDZIC VfB Stuttgart   1514   33 (0,45 b/m)142'. D. BERARDI Sassuolo   15 (6 p.)15   26 (0,58 b/m)142'. BORJA MAYORAL AS Rome   158   43 (0,35 b/m)144'. L. STINDL Borussia M'Gladbach   15 (7 p.)12   39 (0,38 b/m)176'. RAFA MIR SD Huesca   15 (2 p.)12   35 (0,43 b/m)176'. P. AUBAMEYANG Arsenal   15 (2 p.)10   35 (0,43 b/m)181'. L. BAILEY Bayer Leverkusen   159   39 (0,38 b/m)188'. J. VARDY Leicester City   15 (7 p.)13   37 (0,41 b/m)199'. JOÃO PEDRO Cagliari   15 (4 p.)15   36 (0,42 b/m)203'. O. WATKINS Aston Villa   15 (1 p.)13   36 (0,42 b/m)205'

(*) Min/but : temps de jeu moyen entre 2 buts marqués par le joueur
Info : Tous les buts des compétitions officielles sont pris en compte (championnat national, coupe(s) nationale(s), coupes européennes, chp.
du monde des clubs, supercoupe nationale et internationale, play-offs du championnat pour certains pays).
A noter: pour les pays où il existe des play-offs (Belgique, Grèce, Pays-bas, ...), le total de
la colonne 'champ.' correspond uniquement aux buts marqués durant la saison régulière.



#mresu1 { background:#fff; margin:0; width:150px; border-bottom:2px solid #f14; z-index:3; border-radius:0 0 0 4px; }
#mresu1 .mxc { display:block; background:#fff; border:2px solid #E1114B; border-width:0 2px; text-align:left; position:relative; z-index:99999; }
#mresu1 .s4 { padding:0; background-color:#F9CFD9; line-height:5px; height:5px; font-size:1px; margin-top:2px; }
#mresu1 .mx0, .mx1, .mx2, .mx3 { padding:0 4px; color:#f14; font: 13px/14px tahoma,arial; border-bottom:1px solid #F9CFD9; }
#mresu1 .mx0 { border:0; }
#mresu1 .mx1 { font-weight:bold; }
#mresu1 .mx3 { font-size:11px; line-height:13px; }
#mresu1 .mxf { border-bottom:1px solid #fff; }
#mresu1 a { text-decoration:none; display:block; }
#mresu1 a.mx1:hover, #mresu1 a.mx2:hover { background-color:#f14; color:#fff; border-bottom:1px solid #f14; }
#mresu1 a.mx0:hover { background-color:#eee; }
#mresu1 .fl1 { position:relative; top:0px; padding:0 2px 0 0; }

.xb2, .xb3, .xb4, .xb5, .xb6, .xb7 {display:block; overflow:hidden; font-size:0;}
.xb2, .xb3, .xb4, .xb5, .xb6 {height:1px;}
.xb4, .xb5, .xb6, .xb7 {background:#ccc; border-left:1px solid #f14; border-right:1px solid #f14;}
.xb2 {margin:0 6px;}
.xb3 {margin:0 4px;}
.xb4 {margin:0 3px; border-width:0 4px;}
.xb5 {margin:0 2px; border-width:0 3px;}
.xb6 {margin:0 2px; border-width:0 2px;}
.xb7 {margin:0 1px; border-width:0 2px; height:2px;}
.xb2, .xb3 {background:#f14;}
.xb7, .xb6, .xb5, .xb4 {background:#fff;}







Cliquez pour ouvrirle menu complet et afficher les liens vers
 les pages résus/clas./calend. de toutes les compétitions

Qualif. CdM 2022

 FRA - Ligue 1
 FRA - Ligue 2

 ANG - Pr. League
 ALL - Bundesliga
 ESP - Liga
 ITA - Serie A

Champion's League
Europa League

Tous les matchs et résus du jour (live)
Les résultats des jours précédents
Les compétitions des prochains jours



// http://www.faqts.com/knowledge_base/view.phtml/aid/1606
function containsDOM (container, containee) {
  var isParent = false;
  do {
    if ((isParent = container == containee))
      break;
    containee = containee.parentNode;
  }
  while (containee != null);
  return isParent;
}
function checkMouseEnter (element, evt) {
  if (element.contains && evt.fromElement) {
    return !element.contains(evt.fromElement);
  }
  else if (evt.relatedTarget) {
    return !containsDOM(element, evt.relatedTarget);
  }
}
function checkMouseLeave (element, evt) {
  if (element.contains && evt.toElement) {
    return !element.contains(evt.toElement);
  }
  else if (evt.relatedTarget) {
    return !containsDOM(element, evt.relatedTarget);
  }
}




#ico_actu1, #ico_actu2, #ico_actu3, #ico_home1 { background:transparent url(/0_images/sprites_accueil.gif) 0 0 no-repeat; }
#ico_actu1 { background-position:0 0; width:15px; height:15px; }
#ico_actu2 { background-position:-16px 0; width:15px; height:15px; }
#ico_actu3 { background-position:-32px 0; width:18px; height:18px; }
.tab2 { border-top:5px solid #7CB801; background-color:#f0f0f0; border-bottom:1px dotted #999; border-collapse:collapse; }
.tab3 { border-top:5px solid #FED32E; background-color:#f0f0f0; border-bottom:1px dotted #999; }
.tab4 { border-top:5px solid #669; background-color:#f0f0f0; border-bottom:1px dotted #999; }
.w300 { width:300px; }
.tab2 td { padding:0; vertical-align:middle; }
.tab2 td.c1 { padding-left:4px; }
.tab2 td.c2, .c2 { font:bold 15px/22px tahoma,Trebuchet MS; color:#625E7F; text-decoration:none; vertical-align:top; padding-left:4px; }




.listeInfo3 { font:11px/15px arial,verdana; padding:3px 0 0px 0; color:#006; }
.listeInfo3 b { color:#fe0000; padding:0 4px 0 1px; }
.listeInfo3 i { font-weight:bold; font-style:normal; }
.listeInfo3 a { text-decoration:none; display:block; color:#006; }
.listeInfo3 a:hover { color:#D60000; background-color:#FFC9A5; }
.listeInfo-scroll3{ display:block; width:300px; height:120px; overflow:hidden; overflow-x:hidden;
 overflow-y:auto; overflow:-moz-scrollbars-vertical; }
.listeInfo-scroll4{ display:block; width:300px; height:90px; overflow:hidden; }



 Actu et transferts 24h/24



19h02PSG : Herrera préféré à Draxler ?18h55Chelsea : Kanté, Tuchel l'adore !18h38PSG : Mbappé, Larqué s'agace !18h20PSG : la stat qui fait peur...17h55LdC : Man City-PSG, les compos probables17h50PSG : Courbis veut des Parisiens patients17h34City-PSG : quel est le score le plus parié ?17h27Man Utd : Roy Keane conseille deux recrues17h11PSG : les efforts, Riolo attend une réponse17h04PSG : Mbappé devrait débuter sur le banc !16h54Lorient : Abergel plaît à Anderlecht16h38PSG : la visite de Sir Alex Ferguson16h16Bayern : Javi Martinez va quitter le club (off.)15h55Roma : les premiers mots de Mourinho15h47OM : Thauvin, le grand rôle joué par Sampaoli15h24Roma : Mourinho sera le prochain coach ! (off.)15h20PSG : la cote d'une qualification augmente !15h17PSG : à l'extérieur, Rothen croit à l'exploit14h58OM : la 5e place, Baup pessimiste14h22Inter : Djorkaeff applaudit Lukaku14h02Hyères : Anelka s'en va déjà13h42OM : un ailier de Boca dans le viseur13h18Real : 3 retours dans le groupe face à Chelsea12h55Juve : Ronaldo, l'hommage de RabiotVoir les brèves précédentes




 Les + populaires du moment


03/05Lyon : pour Micoud, Lopes est un "danger"03/05Lyon : Aulas félicite Garcia... à sa manière03/05Lyon : Lopes fait la leçon aux Monégasques02/05VIDEO : "bagarre générale" après ASM-OL !03/05Monaco : le club répond à Aulas !03/05PSG : le beau geste de Kean03/05Lyon : Garcia en route vers la Russie ?03/05Juve : Rabiot évoque son changement physique




if (ad1) { document.write('<div id="crt-4fe333d0" style="width:300px;height:250px;"></div>'); }



googletag.cmd.push(function() {  googletag.display('div-gpt-ad-1361436935582-0'); });





Sondage Maxifoot

div#boite1 { font-family:verdana; color:#fff; font-size:11px; line-height:14px; background:#1E2458;
padding:8px 3px 0 3px; }
div#boite1 .b1 { font-weight:bold; margin:4px; cursor:hand; }
div#boite1 .r1 { display:inline-block; padding:4px; }
div#boite1 .r2 { padding:0 4px; }

div#boite1 .bar1 { background:#f14; border-top:2px solid #900; float:left; font:8px/8px arial; height:8px; padding:0; }
div#boite1 .bar2 { background:#fff; width:240px; font-size:1px; margin-top:2px; padding:0; display:inline-block; }
div#boite1 .txt1 { color:#fff; font:12px/12px arial; display:inline-block; padding:0 0 2px 8px; }
div#boite1 a.TextBreves, div#boite1 b a { color:#fff; }
div#boite1 b a { text-decoration:none; font-weight:normal; font-style:italic; }
div#boite1 b a:hover { text-decoration:underline; }
div#boite1 div { padding-bottom:10px; }


function affboite1(ajx){ document.getElementById("boite1").innerHTML=ajx.responseText; }



function vote1(vot1) {
//	return true;
	var form1=document.getElementById('poll1');
	var IDrep=document.getElementsByName('IDrep');
	var rep1=999;
	for (var i=0;i<IDrep.length;i++) {
		if (IDrep[i].checked) {
			rep1=IDrep[i].value;
                        break;
		}
	}
	var data1='vote='+vot1+'&IDpoll=2366&IDrep='+rep1;
	var dat1 = new Date();
	var ajx=newajx('affboite1');
	if (ajx) {
		ajx.open("POST", '//www.maxifoot.fr/sondage/enregistre_vote.php', true);
		ajx.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
		ajx.send('ajax=1&'+data1+'&ts='+dat1.getTime());
	}
	if (window.event) { window.event.cancelBubble=true; }
	return false;
}



In [7]:
len(tr_elements)

100

In [8]:
tr_elements[12].text_content()

'1Atl. Madrid76 pts'

In [10]:
for a in range(len(tr_elements)) :
    if "Butsdont" in tr_elements[a].text_content() :
        print(a)

21
24

In [14]:
tr = tr_elements[24:53]

In [17]:
tr[-1].text_content()

". MORATA Juventus Turin \xa0 18 (2 p.)9 \xa0 41 (0,44 b/m)146'"

In [54]:
tr[-1].

In [18]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re
# Site URL
url="http://www.maxifoot.fr/classement-buteur-europe.htm"

# Make a GET request to fetch the raw HTML content
html_content = requests.get(url).text

# Parse HTML code for the entire site
soup = BeautifulSoup(html_content, "lxml")

In [20]:
gdp = soup.find_all("table")
print("Number of tables on site: ",len(gdp))

Number of tables on site:  32

In [49]:
# Lets go ahead and scrape first table with HTML code gdp[0]
table = gdp[11]
# the head will form our column names
body = table.find_all("tr")
# Head values (Column names) are the first items of the body list
head = body[0] # 0th item is the header row
body_rows = body[1:] # All other items becomes the rest of the rows
body_rows


# Declare empty list to keep Columns names
headings = []
for item in head.find_all("th"): # loop through all th elements
    # convert the th elements to text and strip "\n"
    item = (item.text).rstrip("\n")
    # append the clean column name to headings
    headings.append(item)
print(headings)

['Pl.', 'Joueur', 'Equipe', 'Buts', 'dont champ.', 'Matchs', 'Min/But(*)']

In [50]:
# Next is now to loop though the rest of the rows

#print(body_rows[0])
all_rows = [] # will be a list for list for all rows
for row_num in range(len(body_rows)): # A row at a time
    row = [] # this will old entries for one row
    for row_item in body_rows[row_num].find_all("td"): #loop through all row entries
        # row_item.text removes the tags from the entries
        # the following regex is to remove \xa0 and \n and comma from row_item.text
        # xa0 encodes the flag, \n is the newline and comma separates thousands in numbers
        aa = re.sub("(\xa0)|(\n)|,","",row_item.text)
        #append aa to row - note one row entry is being appended
        row.append(aa)
    # append one row to all_rows
    all_rows.append(row)

In [51]:
df = pd.DataFrame(data=all_rows,columns=headings)
df.head()

,Pl.,Joueur,Equipe,Buts,dont champ.,Matchs,Min/But(*)
0,1.,R. LEWANDOWSKI,Bayern Munich,43 (8 p.),36,37 (116 b/m),73'
1,2.,E. HAALAND,Borussia Dortmund,37 (3 p.),25,38 (097 b/m),88'
2,.,K. MBAPPÉ,Paris SG,37 (9 p.),25,43 (086 b/m),91'
3,4.,L. MESSI,FC Barcelone,36 (7 p.),28,44 (082 b/m),109'
4,5.,CRISTIANO RONALDO,Juventus Turin,34 (9 p.),27,40 (085 b/m),100'

In [52]:
#body

In [ ]:
def get_table_of_players(web) :        
        # Site URL
        url = web

        # Make a GET request to fetch the raw HTML content
        html_content = requests.get(url).text

        # Parse HTML code for the entire site
        soup = BeautifulSoup(html_content, "lxml")


        gdp = soup.find_all("table")


        # Lets go ahead and scrape eleventh table with HTML code gdp[11]
        table = gdp[11]
        # the head will form our column names
        body = table.find_all("tr")
        # Head values (Column names) are the first items of the body list
        head = body[0] # 0th item is the header row
        body_rows = body[1:] # All other items becomes the rest of the rows
        body_rows


        # Declare empty list to keep Columns names
        headings = []
        for item in head.find_all("th"): # loop through all th elements
            # convert the th elements to text and strip "\n"
            item = (item.text).rstrip("\n")
            # append the clean column name to headings
            headings.append(item)


        all_rows = [] # will be a list for list for all rows
        for row_num in range(len(body_rows)): # A row at a time
            row = [] # this will old entries for one row
            for row_item in body_rows[row_num].find_all("td"): #loop through all row entries
                # row_item.text removes the tags from the entries
                # the following regex is to remove \xa0 and \n and comma from row_item.text
                # xa0 encodes the flag, \n is the newline and comma separates thousands in numbers
                aa = re.sub("(\xa0)|(\n)|,","",row_item.text)
                #append aa to row - note one row entry is being appended
                row.append(aa)
            # append one row to all_rows
            all_rows.append(row)

        df = pd.DataFrame(data=all_rows,columns=headings)
        df = pd.DataFrame(data=all_rows,columns=headings)
        year = web.split("-")[-1].split(".htm")[-2]
        if year == "europe" :
            year = 2021
        df["Year"] = [year]*df.shape[0]
        
        liste_joueur_web = soup.find_all('a', class_='jou1')
        
        joueur_web = []
        
        for web in liste_joueur_web :
                joueur_web.append("https://www.maxifoot.fr" + web["href"])
        
        joueur_webb = joueur_web
        
        Age = []
        for w in joueur_webb :
            
            url_joueur = w

            html_content_joueur = requests.get(url_joueur).text

            soup_joueur = BeautifulSoup(html_content_joueur, "lxml")
            
            age_table = soup_joueur.find_all("table")
            
            tab = age_table[16]
            
            bod = tab.find("a")
            
            if bod != None : 
                age = bod.text[:2]
            else :
                age = ""
            Age.append(age)
        
        Age1 = Age
        if len(Age1) == df.shape[0] :
            df["Age"] = Age1
        else :
            Age1 = [""]*(df.shape[0] - len(Age1)) + Age1
            df["Age"] = Age1
        return df